CREATE TABLE [dbo].[Bills]
(
	[BillId] nvarchar(50) NOT NULL PRIMARY KEY,
	[CaseId] int,
	[BillDate] datetime,
	[BillAmount] money,
	[PaidAmount] money,
	[OutStading] money,
	[Intrest] money,
	[WirteOff] money,
	[TransferAmount] money,
	[DoctorId] int,
	[AccountId] int,
	[OfficeId]int,
	[Comment] nvarchar(1000),	
	[ReadingDoctotId] int,
	[BillStatusId] int,
	[FirstVisitDate] datetime,
	[LastVisitDate]  datetime,	
	[LawFirmCaseId] nvarchar(50),
	[IndexNumber] nvarchar(50),
	[PurchasedDate] datetime,
	[TransferBatchId] nvarchar(50),
	[DateOfTransfer] datetime,
	[AssignedLawfirmId] int,
	[HasVerifiCationReceived] bit,
	[HasVerificationSent] bit,
	[HasDenail] bit,
	[HasPayment] bit,
	[SpecialtyId] int,
	[BillNote]  nvarchar(1000),
	[Transfered] bit,
	[TrialDate] Datetime,
	[LawFirmStatus] nvarchar(50),
	[FeeAdded] bit,
	[InvoiceGenerated] bit,
	[StorageFeeAdded] bit,
	[StorageInvoiceGenerated] bit,)
