CREATE TABLE [dbo].[Bills]
(
	[BillId] nvarchar(50) NOT NULL PRIMARY KEY,
	[CaseId] bigint,
	[BillDate] datetime,
	[BillAmount] money,
	[PaidAmount] money,
	[OutStading] money,
	[Intrest] money,
	[WirteOff] money,
	[Transfer] money,
	[DoctorId] bigint,
	[AccountId] bigint,
	[Comment] nvarchar(1000),
	[DiagnosisSetId] nvarchar(1000),
	[ReadingDoctotId] bigint,
	[BillStatusId] bigint,
	[FirstVisitDate] datetime,
	[LastVisitDate]  datetime,
	[CreatedUserId] bigint,
	[UpdatedUserId] bigint,
	[LawFirmCaseId] nvarchar(50),
	[IndexNumber] nvarchar(50),
	[PurchasedDate] datetime,
	[TransferBatchId] nvarchar(50),
	[DateOfTransfer] datetime,
	[AssignedLawfirmId] bigint,
	[HasVerifiCationReceived] bit,
	[HasVerificationSent] bit,
	[HasDenail] bit,
	[HasPayment] bit,
	[SpecialtyId] bigint,
	[BillNote]  nvarchar(1000),
	[Transfered] bit,
	[TrialDate] Datetime,
	[LawFirmStatus] nvarchar(50),
	[FeeAdded] bit,
	[InvoiceGenerated] bit,
	[StorageFeeAdded] bit,
	[StorageInvoiceGenerated] bit,
	[SettelementAmount] money,
	[SettlementDate] Datetime,
	[SettledPrinciple] money,
	[SettledInterest] money,
	[CollectedPrinciple] money,
	[CollectedInterest] money,
	[Venue] nvarchar(50),
	[FirstTrialDate] datetime,
	[FinalTrialDate] datetime,
	[TrialResult] nvarchar(1000),
	[DateOfSettled] datetime,
	[DateOfPRPosted]datetime,
	[Resource] nvarchar(1000),
	[ReconcileImportDate] datetime
	CONSTRAINT [FK_Bill_AssignedLawfirmId] FOREIGN KEY ([AssignedLawfirmId]) REFERENCES [Account](AccountId ),
	CONSTRAINT [FK_Bill_SpecialtyId] FOREIGN KEY ([SpecialtyId]) REFERENCES [Specialty](SpecialtyId ),
	CONSTRAINT [FK_Bill_UpdatedUserId] FOREIGN KEY ([UpdatedUserId]) REFERENCES [User](UserId ),
	CONSTRAINT [FK_Bill_CreatedUserId] FOREIGN KEY ([CreatedUserId]) REFERENCES [User](UserId ),
	CONSTRAINT [FK_Bill_ReadingDoctotId] FOREIGN KEY ([ReadingDoctotId]) REFERENCES [Doctor](DoctorId ),
	CONSTRAINT [FK_Bill_BillStatusId] FOREIGN KEY ([BillStatusId]) REFERENCES [BillStatus](BillStatusId ),
	CONSTRAINT [FK_Bill_DoctorId] FOREIGN KEY ([DoctorId]) REFERENCES [Doctor](DoctorId ),
	CONSTRAINT [FK_Bill_AccountId] FOREIGN KEY ([AccountId]) REFERENCES [Account](AccountId ),
	CONSTRAINT [FK_Bill_CaseId] FOREIGN KEY ([CaseId]) REFERENCES [Case](CaseId),
)
