CREATE TABLE [dbo].[Case]
(
	[CaseId] bigint identity(1,1) NOT NULL PRIMARY KEY,
	[CaseTypeId] bigint ,
	[ProviderID] bigint,
	[InsuranceId] bigint,
	[CaseStatusId] bigint,
	[AttorneyId] bigInt,
	[PatientId] bigint,
	[ClaimNumber] nvarchar(50),
	[PolicyNumber] nvarchar(50),
	[DateOfAccident] datetime,
	[AdjusterId] bigint ,
	[AssociateToDianosisCode] bit,
	[CreatedDate] datetime,
	[AccountId] bigint,
	[InsuranceAddressId] bigint,
	 [CaseNo] BIGINT NULL, 
    [IsDeleted] BIT NULL, 
	[LocationId] bigint,
	[IsCopied] bigint,
	[CopiedAccountId] bigint,
	[CopiedUserId] bigint,
	[CopiedDate] datetime,
	[CopiedFormPatient] bigint,
	[TotalBillAmount] money,
	[Paid] money,
	[Balance] money,
	[CasePrefix] nvarchar(10),
	[RemoteCaseID] nvarchar(50),
	[MarriedStatus] nvarchar(50),
	[ReferringDoctorID] bigint,
	[ReferringProviderId] bigint,
	[DiagnosisForSpecialty] nvarchar(2000),
	[EmployerId] bigint,
	[EmployerAddressId]bigint

	CONSTRAINT [FK_Case_EmployerId] FOREIGN KEY ([EmployerId]) REFERENCES [Employer](EmployerId) ,
	CONSTRAINT [FK_Case_EmployerAddressId] FOREIGN KEY ([EmployerAddressId]) REFERENCES [EmployerAddress](EmployerAddressId) ,
	CONSTRAINT [FK_Case_ReferringProviderId] FOREIGN KEY ([ReferringProviderId]) REFERENCES [Provider](ProviderId) ,
	CONSTRAINT [FK_Case_ReferringDoctorID] FOREIGN KEY ([ReferringDoctorID]) REFERENCES [Doctor](DoctorId) ,
	CONSTRAINT [FK_Case_CopiedFormPatient] FOREIGN KEY ([CopiedFormPatient]) REFERENCES [Patient](PatientId) ,
	CONSTRAINT [FK_Case_CopiedUserId] FOREIGN KEY ([CopiedUserId]) REFERENCES [User](UserId) ,
	  CONSTRAINT [FK_Case_CopiedAccountId] FOREIGN KEY ([CopiedAccountId]) REFERENCES [Account](AccountId) ,
	CONSTRAINT [FK_Case_LocationId] FOREIGN KEY ([LocationId]) REFERENCES [Location](LocationId) , 
    CONSTRAINT [FK_Case_InsuranceAddressId] FOREIGN KEY ([InsuranceAddressId]) REFERENCES [InsuranceAddress](InsuranceAddressId) ,
	    CONSTRAINT [FK_Case_AccountId] FOREIGN KEY ([AccountId]) REFERENCES [Account](AccountId) ,
	    CONSTRAINT [FK_Case_AdjusterId] FOREIGN KEY ([AdjusterId]) REFERENCES [Adjuster](AdjusterId) , 
	    CONSTRAINT [FK_Case_PatientId] FOREIGN KEY ([PatientId]) REFERENCES [Patient](PatientId) ,
	    CONSTRAINT [FK_Case_AttorneyId] FOREIGN KEY ([AttorneyId]) REFERENCES [Attorney](AttorneyId) ,
		CONSTRAINT [FK_Case_CaseTypeId] FOREIGN KEY ([CaseTypeId]) REFERENCES [CaseType](CaseTypeId) ,
		CONSTRAINT [FK_Case_ProviderID] FOREIGN KEY ([ProviderID]) REFERENCES [Provider](ProviderID) ,
		CONSTRAINT [FK_Case_InsuranceId] FOREIGN KEY ([InsuranceId]) REFERENCES [Insurance](InsuranceId) ,
		CONSTRAINT [FK_Case_CaseStatusId] FOREIGN KEY ([CaseStatusId]) REFERENCES [CaseStatus](CaseStatusId)
)
