CREATE TABLE [dbo].[Patient]
(
	[PatientId] bigint identity(1,1) NOT NULL PRIMARY KEY,
	[FirstName] nvarchar(50),
	[MiddleName] nvarchar(50),
	[LastName] nvarchar(50),
	[Age] int,
	[AddressId] bigint,
	[ContactInfoId] bigint,
	[WCBNO] nvarchar(50),
	[SSN] nvarchar(50),
	[DateOfBirth] datetime,
	[Gender] nvarchar(10),
	[JobTitle] nvarchar(50),
	[WorkActivitis] nvarchar(50),
	[CarrierCaseNo] nvarchar(50),
	[EmployerName] nvarchar(100),
	[EmployerAddressId] bigint,
	[EmployerContactInfoId] bigint,
	[UseTranspotation]bit,
	[AccountNo] nvarchar(50),
	[ChartNo] nvarchar(50),
	[PolicyHolder] nvarchar(150),
	[FirstTreatmentDate] datetime,
	[UserId] bigint,
	[IPAddress] nvarchar(25),
	[SourceProcess] nvarchar(50),
    [PolicyHolderAddressId] bigint,
	[PolicyHolderContactInfoId] bigint,
	[AccountId] bigint
	CONSTRAINT [FK_Patient_AccountId] FOREIGN KEY ([AccountId]) REFERENCES [Account](AccountId),
	CONSTRAINT [FK_Patient_UserId] FOREIGN KEY ([UserId]) REFERENCES [User](UserId),
	CONSTRAINT [FK_Patient_ContactId] FOREIGN KEY ([ContactInfoId]) REFERENCES [ContactInfo](ContactInfoId),
	 CONSTRAINT [FK_Patient_AddressId] FOREIGN KEY (AddressId) REFERENCES Address(AddressId), 
	 CONSTRAINT [FK_Patientemp_ContactId] FOREIGN KEY ([ContactInfoId]) REFERENCES [ContactInfo](ContactInfoId),
	 CONSTRAINT [FK_Patientemp_AddressId] FOREIGN KEY (EmployerAddressId) REFERENCES Address(AddressId),
	  CONSTRAINT [FK_Patient_PH_ContactId] FOREIGN KEY ([PolicyHolderAddressId]) REFERENCES [ContactInfo](ContactInfoId),
	 CONSTRAINT [FK_Patient_PH_AddressId] FOREIGN KEY (PolicyHolderContactInfoId) REFERENCES Address(AddressId),


)
