CREATE TABLE [dbo].[Reconcilation]
(
	[ReconcilationId] INT NOT NULL PRIMARY KEY,
	[BillId] nvarchar(50),
	[SettelementAmount] money,
	[SettlementDate] Datetime,
	[SettledPrinciple] money,
	[SettledInterest] money,
	[CollectedPrinciple] money,
	[CollectedInterest] money,
	[Venue] nvarchar(50),
	[FirstTrialDate] datetime,
	[FinalTrialDate] datetime,
	[TrialResult] nvarchar(1000),
	[DateOfSettled] datetime,
	[DateOfPRPosted]datetime,
	[Resource] nvarchar(1000),
	[ReconcileImportDate] datetime,
	[Deleted] bit,
	[CreatedDate] datetime,
	[UpdatedDate] datetime,
	[CreatedBy] int,
	[UpdatedBY]  int,
	IPAddress varchar(15),
)
