CREATE TABLE [dbo].[Role]
(
	[RoleId] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name]	NVARCHAR(50) NOT NULL ,
	IsStandardRole bit NOT NULL DEFAULT(1) ,
	EntityType TINYINT NULL,
	EntityTypeId INT NULL,

)
