CREATE TABLE [dbo].[VisitProcedure]
(
	[VisitProcedureId] int identity(1,1) NOT NULL PRIMARY KEY,
	[VisitId] int ,
	[CaseId] int ,
	[ReScheduleDate] datetime,
	[ReScheduleDateTime] time,	
	[ReportReceived] bit,
	[StudyNumber] nvarchar(50),
	[Notes] nvarchar(1000),
	[ReportPath] nvarchar(max),
	[ReadingDoctor] int,
	[BillStatus] bit,
	[BillNumber] nvarchar(50),
	[Billdate] datetime,
	[Modifier] nvarchar(500),
	[SpecialtyId] int,
	[AccountId] int,
	[Deleted] bit,
	[CreatedDate] datetime,
	[UpdatedDate] datetime,
	[CreatedBy] int,
	[UpdatedBY]  int,
	IPAddress varchar(15),
)
