CREATE TABLE [dbo].[Visits]
(
	[VisitId] int identity(1,1) NOT NULL PRIMARY KEY,
	[CaseId] int ,
	[VisitDate] datetime,
	[VisitStartTime] TIME,
	[VisitEndTime] TIME,
	[Notes] nvarchar(1000),
	[AccountId] int,
	[OfficeId] int,	
	[DoctorID] int ,
	[Status] int,
	[BillStatus] bit,
	[BillDate] datetime,
	[BillNumber] nvarchar(50),
	[VisitTypeId] int,	
	[StudyNumber] nvarchar(20),
	[Transportation] bit,
	[Finalize] bit,
	[AddedByDcotor] bit,
	[CheckInUserId] int,
	[HasProcedureAdded] bit,
	[ManuallyUnFinalized] bit,
	[ClaimNumber] nvarchar(50),
	[PolicyNumber] nvarchar(50),
	[PolicyHolder] nvarchar(100),
	[PolicyHolderAddressId] int,
	[PolicyHolderContactInfoId] int,
	[InsuranceId] int,
	[InsuranceAddressId] int,
	[SpecialtyId] int,
	[Deleted] bit,
	[CreatedDate] datetime,
	[UpdatedDate] datetime,
	[CreatedBy] int,
	[UpdatedBY]  int,
	IPAddress varchar(15),
	
)
