CREATE TABLE [dbo].[VisitProcedure]
(
	[VisitProcedureId] bigint identity(1,1) NOT NULL PRIMARY KEY,
	[VisitId] bigint ,
	[CaseId] bigint ,
	[ReScheduleDate] datetime,
	[ReScheduleDateTime] nvarchar(10),
	[ReScheduleDateType] nvarchar(4),
	[ReportReceived] bit,
	[StudyNumber] nvarchar(50),
	[Notes] nvarchar(1000),
	[ReportPath] nvarchar(max),
	[ReadingDoctor] bigint,
	[BillStatus] bit,
	[BillNumber] nvarchar(50),
	[Billdate] datetime,
	[Modifier] nvarchar(500),
	[SpecialtyId] bigint,
	[AccountId] bigint,
	CONSTRAINT [FK_VisitProcedure_AccountId] FOREIGN KEY ([AccountId]) REFERENCES [Account](AccountId ),
	CONSTRAINT [FK_VisitProcedure_CaseId] FOREIGN KEY ([CaseId]) REFERENCES [Case](CaseId),
	CONSTRAINT [FK_VisitProcedure_SpecialtyId] FOREIGN KEY ([VisitId]) REFERENCES [Visits](VisitId),
	CONSTRAINT [FK_VisitProcedure_ReadingDoctor] FOREIGN KEY ([ReadingDoctor]) REFERENCES [Doctor](DoctorId),
)
