//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttorneyVisit
    {
        public int Id { get; set; }
        public int CalendarEventId { get; set; }
        public int CaseId { get; set; }
        public int PatientId { get; set; }
        public int LocationId { get; set; }
        public int AttorneyId { get; set; }
        public Nullable<System.DateTime> EventStart { get; set; }
        public Nullable<System.DateTime> EventEnd { get; set; }
        public string Subject { get; set; }
        public Nullable<byte> VisitStatusId { get; set; }
        public string ContactPerson { get; set; }
        public int CompanyId { get; set; }
        public string Agenda { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CalendarEvent CalendarEvent { get; set; }
        public virtual Case Case { get; set; }
        public virtual Company Company { get; set; }
        public virtual Location Location { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
    }
}
