//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public string CaseName { get; set; }
        public Nullable<int> CaseTypeId { get; set; }
        public Nullable<decimal> Age { get; set; }
        public System.DateTime DateOfInjury { get; set; }
        public int LocationId { get; set; }
        public int PatientAddressId { get; set; }
        public Nullable<int> PatientContactInfoId { get; set; }
        public Nullable<int> EmpInfo { get; set; }
        public Nullable<int> InsuranceInfoId { get; set; }
        public string VehiclePlateNo { get; set; }
        public Nullable<int> AccidentAddressId { get; set; }
        public string CarrierCaseNo { get; set; }
        public bool Transportation { get; set; }
        public System.DateTime DateOfFirstTreatment { get; set; }
        public Nullable<int> CaseStatusId { get; set; }
        public Nullable<int> AttorneyId { get; set; }
    
        public virtual AddressInfo AddressInfo { get; set; }
        public virtual AddressInfo AddressInfo1 { get; set; }
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual InsuranceInfo InsuranceInfo { get; set; }
        public virtual Location Location { get; set; }
        public virtual PatientEmpInfo PatientEmpInfo { get; set; }
        public virtual User User { get; set; }
    }
}
