//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public string CaseName { get; set; }
        public Nullable<int> CaseTypeId { get; set; }
        public System.DateTime DateOfInjury { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> PatientEmpInfoId { get; set; }
        public Nullable<int> PatientInsuranceInfoId { get; set; }
        public Nullable<int> PatientAccidentInfoId { get; set; }
        public Nullable<int> RefferingOfficeId { get; set; }
        public string CarrierCaseNo { get; set; }
        public bool Transportation { get; set; }
        public Nullable<int> CaseStatusId { get; set; }
        public Nullable<int> AttorneyId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Patient2 Patient2 { get; set; }
        public virtual PatientAccidentInfo PatientAccidentInfo { get; set; }
        public virtual PatientEmpInfo PatientEmpInfo { get; set; }
        public virtual PatientInsuranceInfo PatientInsuranceInfo { get; set; }
        public virtual RefferingOffice RefferingOffice { get; set; }
    }
}
