//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public byte Id { get; set; }
        public string StateCode { get; set; }
        public string CityText { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
