//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMailConfiguration
    {
        public int Id { get; set; }
        public int AppId { get; set; }
        public int QueueTypeId { get; set; }
        public string SmtpClient { get; set; }
        public string SmtpClient_Port { get; set; }
        public string NetworkCredential_EMail { get; set; }
        public string NetworkCredential_Pwd { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual QueueType QueueType { get; set; }
    }
}
