//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int CompanyID { get; set; }
        public int AddressInfoID { get; set; }
        public int ContactInfoID { get; set; }
        public byte LocationType { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual AddressInfo AddressInfo { get; set; }
        public virtual Company Company { get; set; }
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual Location Location2 { get; set; }
    }
}
