//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MIDASGBXEntities : DbContext
    {
        public MIDASGBXEntities()
            : base("name=MIDASGBXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressInfo> AddressInfoes { get; set; }
        public virtual DbSet<AdjusterMaster> AdjusterMasters { get; set; }
        public virtual DbSet<Attorney> Attorneys { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<CaseInsuranceMapping> CaseInsuranceMappings { get; set; }
        public virtual DbSet<CaseStatu> CaseStatus { get; set; }
        public virtual DbSet<CaseType> CaseTypes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanySpecialtyDetail> CompanySpecialtyDetails { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<ContactInfo> ContactInfoes { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<DoctorLocationSchedule> DoctorLocationSchedules { get; set; }
        public virtual DbSet<DoctorSpeciality> DoctorSpecialities { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<InsuranceMaster> InsuranceMasters { get; set; }
        public virtual DbSet<InsuranceType> InsuranceTypes { get; set; }
        public virtual DbSet<Invitation> Invitations { get; set; }
        public virtual DbSet<InvitationType> InvitationTypes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MaritalStatu> MaritalStatus { get; set; }
        public virtual DbSet<OTP> OTPs { get; set; }
        public virtual DbSet<PasswordToken> PasswordTokens { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Patient2> Patient2 { get; set; }
        public virtual DbSet<PatientAccidentInfo> PatientAccidentInfoes { get; set; }
        public virtual DbSet<PatientEmpInfo> PatientEmpInfoes { get; set; }
        public virtual DbSet<PatientFamilyMember> PatientFamilyMembers { get; set; }
        public virtual DbSet<PatientInsuranceInfo> PatientInsuranceInfoes { get; set; }
        public virtual DbSet<PatientType> PatientTypes { get; set; }
        public virtual DbSet<PatientVisit> PatientVisits { get; set; }
        public virtual DbSet<PatientVisitEvent> PatientVisitEvents { get; set; }
        public virtual DbSet<PolicyOwner> PolicyOwners { get; set; }
        public virtual DbSet<RefferingOffice> RefferingOffices { get; set; }
        public virtual DbSet<Relation> Relations { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomTest> RoomTests { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<ScheduleDetail> ScheduleDetails { get; set; }
        public virtual DbSet<SpecialityDetail> SpecialityDetails { get; set; }
        public virtual DbSet<Specialty> Specialties { get; set; }
        public virtual DbSet<SpecialtyDetail> SpecialtyDetails { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<SubscriptionPlan> SubscriptionPlans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserCompany> UserCompanies { get; set; }
        public virtual DbSet<UserCompanyRole> UserCompanyRoles { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
