//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPCompanyMapping
    {
        public int Id { get; set; }
        public string OTP { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime ValidUntil { get; set; }
        public Nullable<int> UsedByCompanyId { get; set; }
        public Nullable<System.DateTime> UsedAtDate { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> OTPForDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
    }
}
