//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient2
    {
        public int id { get; set; }
        public string SSN { get; set; }
        public string WCBNo { get; set; }
        public int LocationID { get; set; }
        public decimal Weight { get; set; }
        public Nullable<byte> MaritalStatus { get; set; }
        public string DrivingLicence { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactRelation { get; set; }
        public string EmergencyContactNumber { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual User User { get; set; }
    }
}
