//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientEmpInfo
    {
        public int Id { get; set; }
        public string JobTitle { get; set; }
        public string EmpName { get; set; }
        public int AddressInfoId { get; set; }
        public int ContactInfoId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int CaseId { get; set; }
        public string Salary { get; set; }
        public Nullable<bool> HourOrYearly { get; set; }
        public Nullable<bool> LossOfEarnings { get; set; }
        public string DatesOutOfWork { get; set; }
        public Nullable<decimal> HoursPerWeek { get; set; }
        public Nullable<bool> AccidentAtEmployment { get; set; }
    
        public virtual AddressInfo AddressInfo { get; set; }
        public virtual Case Case { get; set; }
        public virtual ContactInfo ContactInfo { get; set; }
    }
}
