//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisitEvent
    {
        public int Id { get; set; }
        public int PatientVisitId { get; set; }
        public Nullable<int> SpecialtyId { get; set; }
        public byte ProcedureCodeId { get; set; }
        public Nullable<byte> EventStatusId { get; set; }
        public Nullable<bool> ReportReceived { get; set; }
        public string StudyNumber { get; set; }
        public string Note { get; set; }
        public string ReportPath { get; set; }
        public Nullable<int> ReadingDoctorId { get; set; }
        public Nullable<bool> BillStatus { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string BillNumber { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string Modifier { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual PatientVisit PatientVisit { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
