//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientFamilyMember
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public byte RelationId { get; set; }
        public string FullName { get; set; }
        public string FamilyName { get; set; }
        public string Prefix { get; set; }
        public string Sufix { get; set; }
        public byte Age { get; set; }
        public Nullable<byte> RaceId { get; set; }
        public Nullable<byte> EthnicitesId { get; set; }
        public byte GenderId { get; set; }
        public string CellPhone { get; set; }
        public string WorkPhone { get; set; }
        public Nullable<bool> PrimaryContact { get; set; }
        public Nullable<bool> IsInActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Relation Relation { get; set; }
    }
}
