//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAccidentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientAccidentInfo()
        {
            this.AccidentTreatments = new HashSet<AccidentTreatment>();
            this.AccidentWitnesses = new HashSet<AccidentWitness>();
        }
    
        public int Id { get; set; }
        public int CaseId { get; set; }
        public System.DateTime AccidentDate { get; set; }
        public string PlateNumber { get; set; }
        public string ReportNumber { get; set; }
        public int AccidentAddressInfoId { get; set; }
        public string HospitalName { get; set; }
        public int HospitalAddressInfoId { get; set; }
        public Nullable<System.DateTime> DateOfAdmission { get; set; }
        public string AdditionalPatients { get; set; }
        public string DescribeInjury { get; set; }
        public byte PatientTypeId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string MedicalReportNumber { get; set; }
        public string Weather { get; set; }
        public Nullable<bool> PoliceAtScene { get; set; }
        public string Precinct { get; set; }
        public Nullable<bool> WearingSeatBelts { get; set; }
        public Nullable<bool> AirBagsDeploy { get; set; }
        public Nullable<bool> PhotosTaken { get; set; }
        public string AccidentDescription { get; set; }
        public Nullable<bool> Witness { get; set; }
        public Nullable<bool> Ambulance { get; set; }
        public Nullable<bool> TreatedAndReleased { get; set; }
        public Nullable<bool> Admitted { get; set; }
        public Nullable<bool> XRaysTaken { get; set; }
        public string DurationAtHospital { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccidentTreatment> AccidentTreatments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccidentWitness> AccidentWitnesses { get; set; }
        public virtual AddressInfo AddressInfo { get; set; }
        public virtual AddressInfo AddressInfo1 { get; set; }
        public virtual Case Case { get; set; }
        public virtual PatientType PatientType { get; set; }
    }
}
