//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientVisit()
        {
            this.PatientVisitEvents = new HashSet<PatientVisitEvent>();
        }
    
        public int Id { get; set; }
        public int CaseId { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> SpecialtyId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Notes { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> RefferId { get; set; }
        public Nullable<byte> VisitStatusId { get; set; }
        public Nullable<bool> BillStatus { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string BillNumber { get; set; }
        public Nullable<byte> VisitType { get; set; }
        public Nullable<int> ReschduleId { get; set; }
        public Nullable<System.DateTime> ReschduleDate { get; set; }
        public string StudyNumber { get; set; }
        public Nullable<bool> BillFinalize { get; set; }
        public Nullable<bool> AddedByDoctor { get; set; }
        public Nullable<int> CheckInUserId { get; set; }
        public Nullable<bool> BillManualyUnFinalized { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Location Location { get; set; }
        public virtual Specialty Specialty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientVisitEvent> PatientVisitEvents { get; set; }
    }
}
