//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Referral2()
        {
            this.ReferralDocuments = new HashSet<ReferralDocument>();
            this.ReferralProcedureCodes = new HashSet<ReferralProcedureCode>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PendingReferralId { get; set; }
        public int FromCompanyId { get; set; }
        public Nullable<int> FromLocationId { get; set; }
        public Nullable<int> FromDoctorId { get; set; }
        public Nullable<int> ForSpecialtyId { get; set; }
        public Nullable<int> ForRoomId { get; set; }
        public Nullable<int> ForRoomTestId { get; set; }
        public int ToCompanyId { get; set; }
        public Nullable<int> ToLocationId { get; set; }
        public Nullable<int> ToDoctorId { get; set; }
        public Nullable<int> ToRoomId { get; set; }
        public Nullable<int> ScheduledPatientVisitId { get; set; }
        public Nullable<int> DismissedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int CaseId { get; set; }
        public Nullable<int> FromUserId { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Doctor Doctor1 { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual PatientVisit PatientVisit { get; set; }
        public virtual PendingReferral PendingReferral { get; set; }
        public virtual Room Room { get; set; }
        public virtual Room Room1 { get; set; }
        public virtual RoomTest RoomTest { get; set; }
        public virtual Specialty Specialty { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralDocument> ReferralDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralProcedureCode> ReferralProcedureCodes { get; set; }
    }
}
