//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralDocument
    {
        public int Id { get; set; }
        public int ReferralId { get; set; }
        public int MidasDocumentId { get; set; }
        public string DocumentName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DocumentType { get; set; }
    
        public virtual MidasDocument MidasDocument { get; set; }
        public virtual Referral2 Referral2 { get; set; }
    }
}
