//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSConfiguration
    {
        public int Id { get; set; }
        public int AppId { get; set; }
        public int QueueTypeId { get; set; }
        public string AccountSid { get; set; }
        public string AuthToken { get; set; }
        public bool IsDeleted { get; set; }
    }
}
