//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDAS.GBX.DataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Doctors = new HashSet<Doctor>();
            this.DoctorSpecialities = new HashSet<DoctorSpeciality>();
            this.Invitations = new HashSet<Invitation>();
            this.Patients = new HashSet<Patient>();
            this.UserCompanies = new HashSet<UserCompany>();
            this.UserCompanyRoles = new HashSet<UserCompanyRole>();
        }
    
        public int id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<byte> Gender { get; set; }
        public byte UserType { get; set; }
        public Nullable<byte> UserStatus { get; set; }
        public string ImageLink { get; set; }
        public int AddressId { get; set; }
        public int ContactInfoId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> C2FactAuthEmailEnabled { get; set; }
        public Nullable<bool> C2FactAuthSMSEnabled { get; set; }
    
        public virtual AddressInfo AddressInfo { get; set; }
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<DoctorSpeciality> DoctorSpecialities { get; set; }
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<UserCompany> UserCompanies { get; set; }
        public virtual ICollection<UserCompanyRole> UserCompanyRoles { get; set; }
    }
}
