//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAIdentityServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientAllowedCorsOrigins = new HashSet<ClientAllowedCorsOrigin>();
            this.ClientPostLogoutRedirectURIs = new HashSet<ClientPostLogoutRedirectURI>();
            this.ClientRedirectURIs = new HashSet<ClientRedirectURI>();
            this.ClientScopes = new HashSet<ClientScope>();
            this.ClientSecrets = new HashSet<ClientSecret>();
        }
    
        public int Id { get; set; }
        public string ClientId { get; set; }
        public string ClientName { get; set; }
        public byte Flow { get; set; }
        public string ClientUri { get; set; }
        public bool RequireConsent { get; set; }
        public bool AllowRememberConsent { get; set; }
        public int AccessTokenLifetime { get; set; }
        public byte AccessTokenType { get; set; }
        public int AuthorizationCodeLifetime { get; set; }
        public int IdentityTokenLifetime { get; set; }
        public byte RefreshTokenUsage { get; set; }
        public byte RefreshTokenExpiration { get; set; }
        public int AbsoluteRefreshTokenLifetime { get; set; }
        public int SlidingRefreshTokenLifetime { get; set; }
        public bool UpdateAccessTokenClaimsOnRefresh { get; set; }
        public bool RequireSignOutPrompt { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsTwoFactorAuthentication { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAllowedCorsOrigin> ClientAllowedCorsOrigins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPostLogoutRedirectURI> ClientPostLogoutRedirectURIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientRedirectURI> ClientRedirectURIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientScope> ClientScopes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSecret> ClientSecrets { get; set; }
    }
}
