
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CAIdentityServer.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ClientSecret
{

    public int ID { get; set; }

    public int ClientID { get; set; }

    public string SecretValue { get; set; }



    public virtual Client Client { get; set; }

}

}
