

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CAIdentityServer.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CAIdentityServerEntitiesModel : DbContext
{
    public CAIdentityServerEntitiesModel()
        : base("name=CAIdentityServerEntitiesModel")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<ClientAllowedCorsOrigin> ClientAllowedCorsOrigins { get; set; }

    public virtual DbSet<ClientPostLogoutRedirectURI> ClientPostLogoutRedirectURIs { get; set; }

    public virtual DbSet<ClientRedirectURI> ClientRedirectURIs { get; set; }

    public virtual DbSet<ClientScope> ClientScopes { get; set; }

    public virtual DbSet<Scope> Scopes { get; set; }

    public virtual DbSet<ScopeClaim> ScopeClaims { get; set; }

    public virtual DbSet<ScopeSecret> ScopeSecrets { get; set; }

    public virtual DbSet<ClientSecret> ClientSecrets { get; set; }

}

}

