
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CAIdentityServer.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Scope
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Scope()
    {

        this.ScopeClaims = new HashSet<ScopeClaim>();

        this.ScopeSecrets = new HashSet<ScopeSecret>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public byte ScopeType { get; set; }

    public bool Emphasize { get; set; }

    public bool ShowInDiscoveryDocument { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ScopeClaim> ScopeClaims { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ScopeSecret> ScopeSecrets { get; set; }

}

}
