
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CAIdentityServer.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ScopeClaim
{

    public int Id { get; set; }

    public int ScopeID { get; set; }

    public string Name { get; set; }

    public string ScopeClaimDescription { get; set; }

    public bool AlwaysIncludeInIdToken { get; set; }



    public virtual Scope Scope { get; set; }

}

}
