//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagingServiceManager.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMailConfiguration
    {
        public int Id { get; set; }
        public int ApplicationID { get; set; }
        public string SMTPClientHostName { get; set; }
        public int SmtpClientPortNumber { get; set; }
        public string SMTPClientUserName { get; set; }
        public string SMTPClientPassword { get; set; }
        public bool IsDeleted { get; set; }
        public int MaxNumberOfRetry { get; set; }
        public bool IsSSLEnabled { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
