//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagingServiceManager.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessagingEntities : DbContext
    {
        public MessagingEntities()
            : base("name=MessagingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<EMailConfiguration> EMailConfigurations { get; set; }
        public virtual DbSet<EMailQueue> EMailQueues { get; set; }
        public virtual DbSet<MessageStatu> MessageStatus { get; set; }
        public virtual DbSet<QueueType> QueueTypes { get; set; }
        public virtual DbSet<SMSConfiguration> SMSConfigurations { get; set; }
        public virtual DbSet<SMSQueue> SMSQueues { get; set; }
    }
}
