//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagingServiceManager.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSQueue
    {
        public int Id { get; set; }
        public int ApplicationID { get; set; }
        public int StatusID { get; set; }
        public byte[] SMSObject { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public int NumberOfAttempts { get; set; }
        public string DeliveryResponse { get; set; }
        public string ApplicationName { get; set; }
        public string ToNumber { get; set; }
        public string FromNumber { get; set; }
        public string Message { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual MessageStatu MessageStatu { get; set; }
    }
}
