CREATE TABLE [dbo].[CompanySpecialtyDetails] (
    [id]                  INT            IDENTITY (1, 1) NOT NULL,
    [SpecialtyId]         INT            NULL,
    [CompanyID]           INT            NULL,
    [ReevalDays]          INT            NULL,
    [ReevalVisitCount]    INT            NULL,
    [InitialDays]         INT            NULL,
    [InitialVisitCount]   INT            NULL,
    [MaxReval]            INT            NULL,
    [IsInitialEvaluation] BIT            NULL,
    [Include1500]         BIT            NULL,
    [AssociatedSpecialty] INT            NULL,
    [AllowMultipleVisit]  BIT            NULL,
    [IsDeleted]           BIT            CONSTRAINT [DF_CompanySpecialtyDetails_IsDeleted] DEFAULT ((0)) NULL,
    [CreateByUserID]      INT            NOT NULL,
    [CreateDate]          DATETIME2 (7)  NULL,
    [UpdateByUserID]      INT            NULL,
    [UpdateDate]          DATETIME2 (7)  NULL,
    [InitialCode]         NVARCHAR (250) NULL,
    [ReEvalCode]          NVARCHAR (250) NULL,
    [MandatoryProcCode]   BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CompanySpecialtyDetails] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_CompanySpecialtyDetails_Company] FOREIGN KEY ([CompanyID]) REFERENCES [dbo].[Company] ([id]),
    CONSTRAINT [FK_CompanySpecialtyDetails_Specialty] FOREIGN KEY ([SpecialtyId]) REFERENCES [dbo].[Specialty] ([id]),
    CONSTRAINT [UK_SpecialtyId_CompanyID] UNIQUE NONCLUSTERED ([SpecialtyId] ASC, [CompanyID] ASC)
);

