CREATE TABLE [dbo].[PatientInsuranceInfo] (
    [Id]                            INT             IDENTITY (1, 1) NOT NULL,
    [PolicyHolderName]              NVARCHAR (50)   NULL,
    [PolicyHolderAddressInfoId]     INT             NULL,
    [PolicyHolderContactInfoId]     INT             NULL,
    [PolicyOwnerId]                 TINYINT         NULL,
    [InsuranceCompanyCode]          NVARCHAR (10)   NULL,
    [InsuranceCompanyAddressInfoId] INT             NULL,
    [InsuranceCompanyContactInfoId] INT             NULL,
    [PolicyNo]                      NVARCHAR (50)   NULL,
    [ContactPerson]                 NVARCHAR (50)   NULL,
    [InsuranceTypeId]               TINYINT         NULL,
    [IsInActive]                    BIT             DEFAULT ((0)) NULL,
    [IsDeleted]                     BIT             DEFAULT ((0)) NULL,
    [CreateByUserID]                INT             NOT NULL,
    [CreateDate]                    DATETIME2 (7)   NOT NULL,
    [UpdateByUserID]                INT             NULL,
    [UpdateDate]                    DATETIME2 (7)   NULL,
    [InsuranceMasterId]             INT             NULL,
    [CaseId]                        INT             NOT NULL,
    [InsuranceStartDate]            DATETIME        NULL,
    [InsuranceEndDate]              DATETIME        NULL,
    [BalanceInsuredAmount]          DECIMAL (12, 2) NULL,
    CONSTRAINT [PK_PatientInsuranceInfo] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PatientInsuranceInfo_AddressInfo_InsuranceCompanyAddressInfoId] FOREIGN KEY ([InsuranceCompanyAddressInfoId]) REFERENCES [dbo].[AddressInfo] ([id]),
    CONSTRAINT [FK_PatientInsuranceInfo_AddressInfo_PolicyHolderAddressInfoId] FOREIGN KEY ([PolicyHolderAddressInfoId]) REFERENCES [dbo].[AddressInfo] ([id]),
    CONSTRAINT [FK_PatientInsuranceInfo_Case_CaseId] FOREIGN KEY ([CaseId]) REFERENCES [dbo].[Case] ([Id]),
    CONSTRAINT [FK_PatientInsuranceInfo_ContactInfo_InsuranceCompanyContactInfoId] FOREIGN KEY ([InsuranceCompanyContactInfoId]) REFERENCES [dbo].[ContactInfo] ([id]),
    CONSTRAINT [FK_PatientInsuranceInfo_ContactInfo_PolicyHolderContactInfoId] FOREIGN KEY ([PolicyHolderContactInfoId]) REFERENCES [dbo].[ContactInfo] ([id]),
    CONSTRAINT [FK_PatientInsuranceInfo_InsuranceMaster_InsuranceMasterId] FOREIGN KEY ([InsuranceMasterId]) REFERENCES [dbo].[InsuranceMaster] ([Id]),
    CONSTRAINT [FK_PatientInsuranceInfo_InsuranceType_InsuranceTypeId] FOREIGN KEY ([InsuranceTypeId]) REFERENCES [dbo].[InsuranceType] ([Id]),
    CONSTRAINT [FK_PatientInsuranceInfo_PolicyOwner_PolicyOwnerId] FOREIGN KEY ([PolicyOwnerId]) REFERENCES [dbo].[PolicyOwner] ([Id])
);

