CREATE TABLE [dbo].[PatientFamilyMembers] (
    [Id]             INT           IDENTITY (1, 1) NOT NULL,
    [RelationId]     TINYINT       NOT NULL,
    [FullName]       NVARCHAR (50) NULL,
    [FamilyName]     NVARCHAR (50) NULL,
    [Prefix]         NVARCHAR (10) NULL,
    [Sufix]          NVARCHAR (10) NULL,
    [Age]            TINYINT       NOT NULL,
    [RaceId]         TINYINT       NULL,
    [EthnicitesId]   TINYINT       NULL,
    [GenderId]       TINYINT       NOT NULL,
    [CellPhone]      NVARCHAR (50) NULL,
    [WorkPhone]      NVARCHAR (50) NULL,
    [PrimaryContact] BIT           DEFAULT ((0)) NULL,
    [IsInActive]     BIT           DEFAULT ((0)) NULL,
    [IsDeleted]      BIT           NULL,
    [CreateByUserID] INT           NOT NULL,
    [CreateDate]     DATETIME2 (7) NOT NULL,
    [UpdateByUserID] INT           NULL,
    [UpdateDate]     DATETIME2 (7) NULL,
    [FirstName]      NVARCHAR (50) NULL,
    [MiddleName]     NVARCHAR (50) NULL,
    [LastName]       NVARCHAR (50) NULL,
    [CaseId]         INT           NOT NULL,
    CONSTRAINT [PK_PatientFamilyMembers] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PatientFamilyMembers_Case_CaseId] FOREIGN KEY ([CaseId]) REFERENCES [dbo].[Case] ([Id]),
    CONSTRAINT [FK_PatientFamilyMembers_Gender_GenderId] FOREIGN KEY ([GenderId]) REFERENCES [dbo].[Gender] ([Id]),
    CONSTRAINT [FK_PatientFamilyMembers_Relations_RelationId] FOREIGN KEY ([RelationId]) REFERENCES [dbo].[Relations] ([Id])
);

