CREATE TABLE [dbo].[PatientVisit] (
    [Id]                       INT            IDENTITY (1, 1) NOT NULL,
    [CalendarEventId]          INT            NOT NULL,
    [CaseId]                   INT            NULL,
    [PatientId]                INT            NULL,
    [LocationId]               INT            NOT NULL,
    [RoomId]                   INT            NULL,
    [DoctorId]                 INT            NULL,
    [SpecialtyId]              INT            NULL,
    [EventStart]               DATETIME2 (7)  NULL,
    [EventEnd]                 DATETIME2 (7)  NULL,
    [Notes]                    NVARCHAR (250) NULL,
    [VisitStatusId]            TINYINT        NULL,
    [VisitType]                TINYINT        NULL,
    [IsDeleted]                BIT            DEFAULT ((0)) NULL,
    [CreateByUserID]           INT            NOT NULL,
    [CreateDate]               DATETIME2 (7)  NOT NULL,
    [UpdateByUserID]           INT            NULL,
    [UpdateDate]               DATETIME2 (7)  NULL,
    [IsCancelled]              BIT            DEFAULT ((0)) NULL,
    [IsOutOfOffice]            BIT            DEFAULT ((0)) NULL,
    [LeaveStartDate]           DATETIME2 (7)  NULL,
    [LeaveEndDate]             DATETIME2 (7)  NULL,
    [IsTransportationRequired] BIT            DEFAULT ((0)) NOT NULL,
    [TransportProviderId]      INT            NULL,
    [AncillaryProviderId]      INT            NULL,
    [VisitTypeId]              TINYINT        NULL,
    CONSTRAINT [PK_PatientVisit] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PatientVisit_CalendarEvent_CalendarEventId] FOREIGN KEY ([CalendarEventId]) REFERENCES [dbo].[CalendarEvent] ([Id]),
    CONSTRAINT [FK_PatientVisit_Case_CaseId] FOREIGN KEY ([CaseId]) REFERENCES [dbo].[Case] ([Id]),
    CONSTRAINT [FK_PatientVisit_Company_AncillaryProviderId] FOREIGN KEY ([AncillaryProviderId]) REFERENCES [dbo].[Company] ([id]),
    CONSTRAINT [FK_PatientVisit_Doctor_DoctorId] FOREIGN KEY ([DoctorId]) REFERENCES [dbo].[Doctor] ([Id]),
    CONSTRAINT [FK_PatientVisit_Location_LocationID] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Location] ([id]),
    CONSTRAINT [FK_PatientVisit_Patient_PatientId] FOREIGN KEY ([PatientId]) REFERENCES [dbo].[Patient] ([Id]),
    CONSTRAINT [FK_PatientVisit_Room_RoomId] FOREIGN KEY ([RoomId]) REFERENCES [dbo].[Room] ([id]),
    CONSTRAINT [FK_PatientVisit_Specialty_SpecialtyId] FOREIGN KEY ([SpecialtyId]) REFERENCES [dbo].[Specialty] ([id]),
    CONSTRAINT [FK_PatientVisit_VisitType_VisitTypeId] FOREIGN KEY ([VisitTypeId]) REFERENCES [dbo].[VisitType] ([Id])
);

