CREATE TABLE [dbo].[PlaintiffVehicle] (
    [Id]                                  INT             IDENTITY (1, 1) NOT NULL,
    [CaseId]                              INT             NOT NULL,
    [VehicleNumberPlate]                  NVARCHAR (64)   NOT NULL,
    [State]                               NVARCHAR (64)   NULL,
    [VehicleMakeModel]                    NVARCHAR (64)   NULL,
    [VehicleMakeYear]                     NVARCHAR (32)   NULL,
    [VehicleOwnerName]                    NVARCHAR (128)  NULL,
    [VehicleOperatorName]                 NVARCHAR (128)  NULL,
    [VehicleInsuranceCompanyName]         NVARCHAR (128)  NULL,
    [VehiclePolicyNumber]                 NVARCHAR (64)   NULL,
    [VehicleClaimNumber]                  NVARCHAR (64)   NULL,
    [VehicleLocation]                     NVARCHAR (64)   NULL,
    [VehicleDamageDiscription]            NVARCHAR (1024) NULL,
    [RelativeVehicle]                     BIT             CONSTRAINT [DF_PlaintiffVehicle_RelativeVehicle] DEFAULT ((0)) NULL,
    [RelativeVehicleMakeModel]            NVARCHAR (64)   NULL,
    [RelativeVehicleMakeYear]             NVARCHAR (32)   NULL,
    [RelativeVehicleOwnerName]            NVARCHAR (128)  NULL,
    [RelativeVehicleInsuranceCompanyName] NVARCHAR (128)  NULL,
    [RelativeVehiclePolicyNumber]         NVARCHAR (64)   NULL,
    [VehicleResolveDamage]                BIT             CONSTRAINT [DF_PlaintiffVehicle_VehicleResolveDamage] DEFAULT ((0)) NULL,
    [VehicleDriveable]                    BIT             CONSTRAINT [DF_PlaintiffVehicle_VehicleDriveable] DEFAULT ((0)) NULL,
    [VehicleEstimatedDamage]              DECIMAL (18)    CONSTRAINT [DF_PlaintiffVehicle_VehicleEstimatedDamage] DEFAULT ((0)) NULL,
    [RelativeVehicleLocation]             NVARCHAR (64)   NULL,
    [VehicleClientHaveTitle]              BIT             CONSTRAINT [DF_PlaintiffVehicle_VehicleClientHaveTitle] DEFAULT ((0)) NULL,
    [RelativeVehicleOwner]                NVARCHAR (128)  NULL,
    [IsDeleted]                           BIT             CONSTRAINT [DF_PlaintiffVehicle_IsDeleted] DEFAULT ((0)) NULL,
    [CreateByUserID]                      INT             NOT NULL,
    [CreateDate]                          DATETIME2 (7)   NOT NULL,
    [UpdateByUserID]                      INT             NULL,
    [UpdateDate]                          DATETIME2 (7)   NULL,
    CONSTRAINT [PK_PlaintiffVehicle] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PlaintiffVehicle_Case_CaseId] FOREIGN KEY ([CaseId]) REFERENCES [dbo].[Case] ([Id])
);

