CREATE TABLE [dbo].[PlaintiffVehicle]
(
    [Id] INT NOT NULL IDENTITY(1,1),
    [NumberPlate] NVARCHAR(64) NULL, 
    [State] NVARCHAR(64) NULL, 
    [MakeModel] NVARCHAR(64) NULL, 
    [MakeYear] NVARCHAR(32) NULL, 
    [OwnerName] NVARCHAR(128) NULL, 
    [OperatorName] NVARCHAR(128) NULL, 
    [InsuranceCompanyName] NVARCHAR(128) NULL, 
    [PolicyNumber] NVARCHAR(64) NULL, 
    [ClaimNumber] NVARCHAR(64) NULL, 
    [VehicleLocation] NVARCHAR(64) NULL, 
    [DiscriptionDamageToVehicle] NVARCHAR(1024) NULL, 
    [RelativeOwnsVehicle] BIT NULL DEFAULT 0, 
    [RelativeVehicleMakeModel] NVARCHAR(64) NULL, 
    [RelativeVehicleMakeYear] NVARCHAR(32) NULL, 
    [RelativeVehicleOwner] NVARCHAR(128) NULL, 
    [RelativeVehicleInsuranceCompanyName] NVARCHAR(128) NULL, 
    [RelativeVehiclePolicyNumber] NVARCHAR(64) NULL, 
    [ResolveDamageVehicle] BIT NULL DEFAULT 0, 
    [VehicleDriveable] BIT NULL DEFAULT 0, 
    [EstimatedDamage] DECIMAL NULL DEFAULT 0, 
    [RelativeVehicleLocation] NVARCHAR(64) NULL, 
    [ClientHaveTitleToVehicle] BIT NULL DEFAULT 0, 
    [OwnerRelativeVehicle] NVARCHAR(128) NULL, 

    [IsDeleted] [BIT] NULL DEFAULT 0,
	[CreateByUserID] [INT] NOT NULL,
	[CreateDate] [DATETIME2](7) NOT NULL,
	[UpdateByUserID] [INT] NULL,
	[UpdateDate] [DATETIME2](7) NULL, 
    CONSTRAINT [PK_PlaintiffVehicle] PRIMARY KEY ([Id])
)
