export enum Races {
    AMERICAN_INDIAN_OR_ALASKA_NATIVE = 1,
    ASIAN = 2,
    BLACK_OR_AFRICAN_AMERICAN = 3,
    NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER = 4,
    WHITE = 5,
    DECLINED_TO_SPECIFY = 6
}
