//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANotificationService.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserConnection
    {
        public string Id { get; set; }
        public string UserAgent { get; set; }
        public string UserName { get; set; }
    
        public virtual User User { get; set; }
    }
}
