//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace GBDataRepository.Model
=======
namespace Midas.GreenBill.Model
>>>>>>> master
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillStatusHistory
    {
        public int BillStatusHistoryId { get; set; }
        public Nullable<int> BillId { get; set; }
        public Nullable<int> LastStatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBY { get; set; }
        public string IPAddress { get; set; }
    }
}
