//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.GreenBill.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string BillId { get; set; }
        public Nullable<int> CaseId { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> OutStading { get; set; }
        public Nullable<decimal> Intrest { get; set; }
        public Nullable<decimal> WirteOff { get; set; }
        public Nullable<decimal> TransferAmount { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ReadingDoctotId { get; set; }
        public Nullable<int> BillStatusId { get; set; }
        public Nullable<System.DateTime> FirstVisitDate { get; set; }
        public Nullable<System.DateTime> LastVisitDate { get; set; }
        public string LawFirmCaseId { get; set; }
        public string IndexNumber { get; set; }
        public Nullable<System.DateTime> PurchasedDate { get; set; }
        public string TransferBatchId { get; set; }
        public Nullable<System.DateTime> DateOfTransfer { get; set; }
        public Nullable<int> AssignedLawfirmId { get; set; }
        public Nullable<bool> HasVerifiCationReceived { get; set; }
        public Nullable<bool> HasVerificationSent { get; set; }
        public Nullable<bool> HasDenail { get; set; }
        public Nullable<bool> HasPayment { get; set; }
        public Nullable<int> SpecialtyId { get; set; }
        public string BillNote { get; set; }
        public Nullable<bool> Transfered { get; set; }
        public Nullable<System.DateTime> TrialDate { get; set; }
        public string LawFirmStatus { get; set; }
        public Nullable<bool> FeeAdded { get; set; }
        public Nullable<bool> InvoiceGenerated { get; set; }
        public Nullable<bool> StorageFeeAdded { get; set; }
        public Nullable<bool> StorageInvoiceGenerated { get; set; }
    }
}
