//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.GreenBill.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseDocument
    {
        public long CaseDocumentId { get; set; }
        public Nullable<long> CaseId { get; set; }
        public Nullable<long> CaseTypeId { get; set; }
        public Nullable<bool> IsRecieved { get; set; }
        public string AssignTo { get; set; }
        public Nullable<System.DateTime> AssignOn { get; set; }
        public string Status { get; set; }
        public string DocumentTypeId { get; set; }
        public Nullable<int> NodeId { get; set; }
    }
}
