//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.GreenBill.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int CaseId { get; set; }
        public Nullable<int> CaseTypeId { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> InsuranceId { get; set; }
        public Nullable<int> CaseStatusId { get; set; }
        public Nullable<int> AttorneyId { get; set; }
        public Nullable<int> PatientDetailId { get; set; }
        public string ClaimNumber { get; set; }
        public string PolicyNumber { get; set; }
        public Nullable<System.DateTime> DateOfAccident { get; set; }
        public Nullable<int> AdjusterId { get; set; }
        public Nullable<bool> AssociateToDianosisCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> InsuranceAddressId { get; set; }
        public Nullable<int> CaseNo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> IsCopied { get; set; }
        public Nullable<int> CopiedAccountId { get; set; }
        public Nullable<int> CopiedUserId { get; set; }
        public Nullable<System.DateTime> CopiedDate { get; set; }
        public Nullable<int> CopiedFormPatient { get; set; }
        public Nullable<bool> IsSoftDeleted { get; set; }
        public Nullable<decimal> TotalBillAmount { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string RemoteCaseID { get; set; }
        public string MarriedStatus { get; set; }
        public Nullable<int> ReferringDoctorID { get; set; }
        public Nullable<int> ReferringProviderId { get; set; }
        public string DiagnosisForSpecialty { get; set; }
        public Nullable<int> EmployerId { get; set; }
        public Nullable<int> EmployerAddressId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBY { get; set; }
    }
}
