//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.CaseDiagnosisSpecialities = new HashSet<CaseDiagnosisSpeciality>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CaseTypeId { get; set; }
        public Nullable<int> MedicalFacilitiesID { get; set; }
        public Nullable<int> PatientInsuranceId { get; set; }
        public Nullable<int> CaseStatusId { get; set; }
        public Nullable<int> AttorneyId { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string ClaimNumber { get; set; }
        public Nullable<System.DateTime> DateOfAccident { get; set; }
        public Nullable<int> AdjusterId { get; set; }
        public Nullable<System.DateTime> CaseDate { get; set; }
        public Nullable<int> CaseNo { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<bool> IsSoftDeleted { get; set; }
        public string RemoteCaseID { get; set; }
        public Nullable<int> ReferringProviderId { get; set; }
        public Nullable<int> EmployerId { get; set; }
        public Nullable<int> EmployerAddressId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Case Case1 { get; set; }
        public virtual Case Case2 { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual EmployerAddress EmployerAddress { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseDiagnosisSpeciality> CaseDiagnosisSpecialities { get; set; }
    }
}
