//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CyclicProcedureConfigurationAmount
    {
        public int cpca { get; set; }
        public int csc { get; set; }
        public string AccountId { get; set; }
        public Nullable<int> ProcdureCodeId { get; set; }
        public int Count { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public decimal Percent { get; set; }
        public string Type { get; set; }
    }
}
