//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorDetail
    {
<<<<<<< HEAD:Midas/DataAccessServices/GBDataRepository/Model/Doctor.cs
        public int ID { get; set; }
        public Nullable<int> DoctorUserId { get; set; }
        public string SpecialityID { get; set; }
=======
        public int DoctorDetailId { get; set; }
        public Nullable<int> DoctorUserId { get; set; }
>>>>>>> master:Midas/DataAccessServices/GBDataRepository/Model/DoctorDetail.cs
        public string LicenseNumber { get; set; }
        public string WCBAuthorization { get; set; }
        public string WcbRatingCode { get; set; }
        public string NPI { get; set; }
        public string FederalTaxId { get; set; }
        public Nullable<byte> TaxType { get; set; }
        public string AssignNumber { get; set; }
        public string Title { get; set; }
<<<<<<< HEAD:Midas/DataAccessServices/GBDataRepository/Model/Doctor.cs
        public Nullable<byte> DoctorType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
=======
        public Nullable<int> EIN_SIN { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBY { get; set; }
>>>>>>> master:Midas/DataAccessServices/GBDataRepository/Model/DoctorDetail.cs
    }
}
