//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentType
    {
        public int DocumentTypeId { get; set; }
        public string Type { get; set; }
        public Nullable<int> AbbreviationId { get; set; }
        public Nullable<int> NodeId { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> MergeInPacket { get; set; }
        public Nullable<int> AssignUserID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBY { get; set; }
        public string IPAddress { get; set; }
    }
}
