//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailProfile
    {
        public int ID { get; set; }
        public string ProfileName { get; set; }
        public string SMTPServer { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public Nullable<bool> SSLEnabled { get; set; }
        public string AuthenticationUsername { get; set; }
        public string Password { get; set; }
        public bool SMTPAuthenticationRequired { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
