//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvelopeConfiguration
    {
        public int EnvelopeConfigurationId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<bool> IsCompanyName { get; set; }
        public Nullable<bool> IsAddressStreet1 { get; set; }
        public Nullable<bool> IsAddressStreet2 { get; set; }
        public Nullable<bool> IsAddressCity { get; set; }
        public Nullable<bool> IsAddressZip { get; set; }
        public Nullable<bool> IsAddressState { get; set; }
        public string EnvelopeDisplayName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
