//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.GreenBill.Model
{
    using GBDataRepository.Model;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class GreenBillsDbEntities : DbContext
    {
        public GreenBillsDbEntities(string connectionString)
            : base("name=GreenBillsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Abbreviation> Abbreviation { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<GBDataRepository.Model.Action> Action { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<ApplicationSettings> ApplicationSettings { get; set; }
        public virtual DbSet<BillDetails> BillDetails { get; set; }
        public virtual DbSet<BillPom> BillPom { get; set; }
        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<BillStatus> BillStatus { get; set; }
        public virtual DbSet<BillVerification> BillVerification { get; set; }
        public virtual DbSet<BillVerificationAnswer> BillVerificationAnswer { get; set; }
        public virtual DbSet<Case> Case { get; set; }
        public virtual DbSet<CaseDocument> CaseDocument { get; set; }
        public virtual DbSet<CaseStatus> CaseStatus { get; set; }
        public virtual DbSet<CaseType> CaseType { get; set; }
        public virtual DbSet<ContactInfo> ContactInfo { get; set; }
        public virtual DbSet<DenialReasons> DenialReasons { get; set; }
        public virtual DbSet<DiagnosisType> DiagnosisType { get; set; }
        public virtual DbSet<DignosisCode> DignosisCode { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<DoctorMedProvider> DoctorMedProvider { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<EmailFields> EmailFields { get; set; }
        public virtual DbSet<EmailProfile> EmailProfile { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplate { get; set; }
        public virtual DbSet<Employer> Employer { get; set; }
        public virtual DbSet<EmployerAddress> EmployerAddress { get; set; }
        public virtual DbSet<Insurance> Insurance { get; set; }
        public virtual DbSet<InsuranceAddress> InsuranceAddress { get; set; }
        public virtual DbSet<IntakeAOB> IntakeAOB { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<MedicalFacilities> MedicalFacilities { get; set; }
        public virtual DbSet<Nodes> Nodes { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PatientAccidentDetails> PatientAccidentDetails { get; set; }
        public virtual DbSet<PatientInsurance> PatientInsurance { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<PaymentImages> PaymentImages { get; set; }
        public virtual DbSet<POM> POM { get; set; }
        public virtual DbSet<ProcedureCode> ProcedureCode { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<ProviderMedicalFacilities> ProviderMedicalFacilities { get; set; }
        public virtual DbSet<Reconcilation> Reconcilation { get; set; }
        public virtual DbSet<RequiredDocuments> RequiredDocuments { get; set; }
        public virtual DbSet<RoleActions> RoleActions { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<RoomSchedule> RoomSchedule { get; set; }
        public virtual DbSet<Specialty> Specialty { get; set; }
        public virtual DbSet<SpecialtyDetails> SpecialtyDetails { get; set; }
        public virtual DbSet<SystemSetting> SystemSetting { get; set; }
        public virtual DbSet<SystemSettingKey> SystemSettingKey { get; set; }
        public virtual DbSet<TransferredCases> TransferredCases { get; set; }
        public virtual DbSet<Transportation> Transportation { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<VerificationAnswerImages> VerificationAnswerImages { get; set; }
        public virtual DbSet<VerificationImages> VerificationImages { get; set; }
        public virtual DbSet<VisitProcedure> VisitProcedure { get; set; }
        public virtual DbSet<Visits> Visits { get; set; }
        public virtual DbSet<VisitType> VisitType { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<AuditTrail> AuditTrail { get; set; }
        public virtual DbSet<BillStatusHistory> BillStatusHistory { get; set; }
        public virtual DbSet<CaseAssociatedDiagnosisCode> CaseAssociatedDiagnosisCode { get; set; }
        public virtual DbSet<CompanyConnections> CompanyConnections { get; set; }
        public virtual DbSet<CyclicInsuranceConfiguration> CyclicInsuranceConfiguration { get; set; }
        public virtual DbSet<CyclicProcedureConfigurationAmount> CyclicProcedureConfigurationAmount { get; set; }
        public virtual DbSet<CyclicSpecialtyConfiguration> CyclicSpecialtyConfiguration { get; set; }
        public virtual DbSet<CyclicSpecialtyConfigurationAmount> CyclicSpecialtyConfigurationAmount { get; set; }
        public virtual DbSet<EnvelopeConfiguration> EnvelopeConfiguration { get; set; }
        public virtual DbSet<GeneralDenialImages> GeneralDenialImages { get; set; }
        public virtual DbSet<GeneralDenials> GeneralDenials { get; set; }
        public virtual DbSet<Mandatory> Mandatory { get; set; }
        public virtual DbSet<Notes> Notes { get; set; }
        public virtual DbSet<NotesType> NotesType { get; set; }
        public virtual DbSet<PacketRequest> PacketRequest { get; set; }
        public virtual DbSet<PacketRequestBills> PacketRequestBills { get; set; }
        public virtual DbSet<Reminder> Reminder { get; set; }
        public virtual DbSet<ReminderRecurrence> ReminderRecurrence { get; set; }
        public virtual DbSet<ReminderType> ReminderType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleActivityEvents> RoleActivityEvents { get; set; }
        public virtual DbSet<RoleEvents> RoleEvents { get; set; }
        public virtual DbSet<SignOnPdf> SignOnPdf { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
