//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntakeAOB
    {
        public int IntakeAOBId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> PatinetId { get; set; }
        public Nullable<int> CaseTypeId { get; set; }
    }
}
