//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public int NodeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string NodeName { get; set; }
        public string ParentName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> AllowToDeleteDocument { get; set; }
        public int AccountId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBY { get; set; }
    }
}
