//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacketRequestBill
    {
        public int PacketRequestBills { get; set; }
        public Nullable<int> PacketRequestId { get; set; }
        public Nullable<int> BillId { get; set; }
    }
}
