//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.GreenBill.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDetail
    {
        public int PatientDetailId { get; set; }
        public Nullable<int> UserPatientId { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> Age { get; set; }
        public string WCBNO { get; set; }
        public string JobTitle { get; set; }
        public string WorkActivitis { get; set; }
        public string CarrierCaseNo { get; set; }
        public string EmployerName { get; set; }
        public Nullable<int> EmployerAddressId { get; set; }
        public Nullable<int> EmployerContactInfoId { get; set; }
        public Nullable<bool> UseTranspotation { get; set; }
        public string AccountNo { get; set; }
        public string ChartNo { get; set; }
        public string PolicyHolder { get; set; }
        public Nullable<System.DateTime> FirstTreatmentDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IPAddress { get; set; }
        public string SourceProcess { get; set; }
        public Nullable<int> PolicyHolderAddressId { get; set; }
        public Nullable<int> PolicyHolderContactInfoId { get; set; }
        public Nullable<int> InsuranceId { get; set; }
        public Nullable<int> InsuranceAddressId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBY { get; set; }
    }
}
