//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureCode
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string LongDescription { get; set; }
        public string Modifier { get; set; }
        public string RVU { get; set; }
        public string ValueCode { get; set; }
        public string LongModifier { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> SpecialtyId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Specialty Specialty { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
