//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.GreenBill.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureCode
    {
        public int ProcedureCodeId { get; set; }
        public string code { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsBilable { get; set; }
        public Nullable<bool> ShowToDoctor { get; set; }
        public Nullable<bool> IsAddedToPreferredList { get; set; }
        public string LongDescription { get; set; }
        public string Modifier { get; set; }
        public string RVU { get; set; }
        public string ValueCode { get; set; }
        public string LongModifier { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> SpecialtyId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBY { get; set; }
        public string IPAddress { get; set; }
    }
}
