//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderMedicalFacility
    {
        public int ID { get; set; }
        public int ProviderID { get; set; }
        public int MedicalFacilityID { get; set; }
        public int BillingAdressID { get; set; }
        public int TreatingAddressID { get; set; }
        public int BillingContactInfoID { get; set; }
        public int TreatingContactInfoID { get; set; }
        public bool IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual ContactInfo ContactInfo1 { get; set; }
        public virtual MedicalFacility MedicalFacility { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
