//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.GreenBill.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int RemindeId { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public string ReminderDesc { get; set; }
        public Nullable<int> ReminderAssignTo { get; set; }
        public Nullable<int> ReminderAssignBy { get; set; }
        public Nullable<int> ReminderStatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsRecurrence { get; set; }
        public Nullable<int> RecurrenceType { get; set; }
        public Nullable<int> OccurrenceEndCount { get; set; }
        public Nullable<int> DayOption { get; set; }
        public Nullable<int> DayCount { get; set; }
        public Nullable<int> EveryWeekday { get; set; }
        public Nullable<int> RecurWeekCount { get; set; }
        public Nullable<int> Sunday { get; set; }
        public Nullable<int> Monday { get; set; }
        public Nullable<int> Tuesday { get; set; }
        public Nullable<int> Wednesday { get; set; }
        public Nullable<int> Thursday { get; set; }
        public Nullable<int> Friday { get; set; }
        public Nullable<int> Saturday { get; set; }
        public Nullable<int> MonthOption { get; set; }
        public Nullable<int> CaseId { get; set; }
        public Nullable<int> DocterId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string DismissReason { get; set; }
        public string ShowOn { get; set; }
        public Nullable<int> ReminderTypeId { get; set; }
        public string ReminderType { get; set; }
        public Nullable<int> EndDateCount { get; set; }
    }
}
