//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderRecurrence
    {
        public int RecurrenceId { get; set; }
        public int ReminderId { get; set; }
        public System.DateTime ReminderDate { get; set; }
        public Nullable<int> RecurrenceType { get; set; }
        public Nullable<bool> DismissStatus { get; set; }
    }
}
