//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace GBDataRepository.Model
=======
namespace Midas.GreenBill.Model
>>>>>>> master
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignOnPdf
    {
        public int Id { get; set; }
        public string PdfType { get; set; }
        public string PdfSignPath { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> AccountId { get; set; }
    }
}
