//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialtyDetail
    {
        public int ID { get; set; }
        public int SpecialtyId { get; set; }
        public Nullable<bool> IsUnitApply { get; set; }
        public Nullable<int> FollowUpDays { get; set; }
        public Nullable<int> FollowupTime { get; set; }
        public Nullable<int> InitialDays { get; set; }
        public Nullable<int> InitialTime { get; set; }
        public Nullable<bool> IsInitialEvaluation { get; set; }
        public Nullable<bool> Include1500 { get; set; }
        public Nullable<int> AssociatedSpecialty { get; set; }
        public Nullable<bool> AllowMultipleVisit { get; set; }
        public Nullable<int> MedicalOfficeId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreateByUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual MedicalFacility MedicalFacility { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
