//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.GreenBill.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User1
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public byte UserType { get; set; }
        public string Notes { get; set; }
        public string Picture { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> ContactInfoId { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Password { get; set; }
        public string EmployerCode { get; set; }
        public Nullable<bool> DefaultAttoreny { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBY { get; set; }
    }
}
