//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDataRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int VisitId { get; set; }
        public Nullable<int> CaseId { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.TimeSpan> VisitStartTime { get; set; }
        public Nullable<System.TimeSpan> VisitEndTime { get; set; }
        public string Notes { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> BillStatus { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string BillNumber { get; set; }
        public Nullable<int> VisitTypeId { get; set; }
        public string StudyNumber { get; set; }
        public Nullable<bool> Transportation { get; set; }
        public Nullable<bool> Finalize { get; set; }
        public Nullable<bool> AddedByDcotor { get; set; }
        public Nullable<int> CheckInUserId { get; set; }
        public Nullable<bool> HasProcedureAdded { get; set; }
        public Nullable<bool> ManuallyUnFinalized { get; set; }
        public string ClaimNumber { get; set; }
        public string PolicyNumber { get; set; }
        public string PolicyHolder { get; set; }
        public Nullable<int> PolicyHolderAddressId { get; set; }
        public Nullable<int> PolicyHolderContactInfoId { get; set; }
        public Nullable<int> ReferringOfficeID { get; set; }
        public Nullable<int> InsuranceId { get; set; }
        public Nullable<int> InsuranceAddressId { get; set; }
        public Nullable<int> SpecialtyId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBY { get; set; }
        public string IPAddress { get; set; }
    }
}
