

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class Company
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Company()
    {

        this.UserCompanies = new HashSet<UserCompany>();

    }


    public int id { get; set; }

    public string Name { get; set; }

    public byte Status { get; set; }

    public int CompanyType { get; set; }

    public Nullable<int> SubscriptionPlanType { get; set; }

    public string TaxID { get; set; }

    public int AddressId { get; set; }

    public int ContactInfoID { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public int CreateByUserID { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<int> UpdateByUserID { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<int> BlobStorageTypeId { get; set; }

    public int CompanyStatusTypeID { get; set; }



    public virtual CompanyStatusType CompanyStatusType { get; set; }

    public virtual CompanyType CompanyType1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserCompany> UserCompanies { get; set; }

}


public partial class CompanyStatusType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CompanyStatusType()
    {

        this.Companies = new HashSet<Company>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Company> Companies { get; set; }

}


public partial class CompanyType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CompanyType()
    {

        this.Companies = new HashSet<Company>();

    }


    public int id { get; set; }

    public string Name { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public int CreateByUserID { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<int> UpdateByUserID { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Company> Companies { get; set; }

}


public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.UserCompanies = new HashSet<UserCompany>();

        this.UserCompanyRoles = new HashSet<UserCompanyRole>();

    }


    public int id { get; set; }

    public string UserName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public Nullable<byte> Gender { get; set; }

    public byte UserType { get; set; }

    public Nullable<byte> UserStatus { get; set; }

    public string ImageLink { get; set; }

    public int AddressId { get; set; }

    public int ContactInfoId { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public string Password { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public int CreateByUserID { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<int> UpdateByUserID { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<bool> C2FactAuthEmailEnabled { get; set; }

    public Nullable<bool> C2FactAuthSMSEnabled { get; set; }



    public virtual UserType UserType1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserCompany> UserCompanies { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserCompanyRole> UserCompanyRoles { get; set; }

}


public partial class UserApiRoleMapping
{

    public int ID { get; set; }

    public string API { get; set; }

    public string ROLES { get; set; }

    public string METHODS { get; set; }

}


public partial class UserCompany
{

    public int id { get; set; }

    public int UserID { get; set; }

    public int CompanyID { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public int CreateByUserID { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<int> UpdateByUserID { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public bool IsAccepted { get; set; }

    public int UserStatusID { get; set; }



    public virtual Company Company { get; set; }

    public virtual User User { get; set; }

    public virtual UserStatus UserStatu { get; set; }

}


public partial class UserCompanyRole
{

    public int id { get; set; }

    public int UserID { get; set; }

    public int RoleID { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public int CreateByUserID { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<int> UpdateByUserID { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }



    public virtual User User { get; set; }

}


public partial class UserStatus
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserStatus()
    {

        this.UserCompanies = new HashSet<UserCompany>();

    }


    public int ID { get; set; }

    public string NAME { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserCompany> UserCompanies { get; set; }

}


public partial class UserType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserType()
    {

        this.Users = new HashSet<User>();

    }


    public byte id { get; set; }

    public string Name { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public int CreateByUserID { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<int> UpdateByUserID { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<User> Users { get; set; }

}

